version: "3.9"

services:
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    container_name: "${APP_NAME}_nginx"
    ports:
      - "80:80"
    volumes:
      - ./source:/var/www/html:delegated
      - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql

  #Php Service

  app:
    build:
      context: ./compose/php
    container_name: ${APP_NAME}_app
    ports: 
      - "9000:9000"
    volumes:
      - ./source:/var/www/html:delegated
      - ./compose/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    platform: linux/x86_64
    image: mysql:8
    restart: unless-stopped
    container_name: "${APP_NAME}_mysql"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_NAME: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
    restart: always
    depends_on:
      - mysql
    ports:
      - "8085:80"
    volumes:
      - /sessions
    links:
      - mysql

